### ISSUE TITLE
360 Video Texture Flipped Horizontally

### ISSUE THREAD

**Issue by deshan** [fbsamples/360-video-player-for-android#10]
@03lafaye  Thanks for sharing this superb work with the community.

Hi all,
I managed to run this project successfully and play 360 video. Everything ok except I notice that the video texture is flipped. Please see the attached image.

Please help with fixing this
Thanks

![screenshot_20170329-163743](https://cloud.githubusercontent.com/assets/234754/24451952/9d6da2f2-149e-11e7-95a2-3c258e2b4edb.png)

**Comment by 03lafaye** [comment]
You can flip horizontally in the vertex shader:
`gl_Position = uMVPMatrix * aPosition * vec4(1, -1, 1, 1);` just negate the x component.

**Comment by deshan** [comment]
Thanks @03lafaye 
It worked, But I noticed a updown flipping and had to do negate the y of up vector also.

Matrix.setLookAtM(
                    viewMatrix,
                    0,
                    camera[0], camera[1], camera[2], 	
                    0, 0, 0, 	
                    0, -1, 0								/* Up vector negate*/			
            );
