### ISSUE TITLE
Does not play video in Samsung note 4, SM-N900,v4.4.2

### ISSUE THREAD

**Issue by Qamar4P** [fbsamples/360-video-player-for-android#2]
I have build this. 360 video player in Android Studio v2.1 beta3. gradle:2.1.0-beta3
Can't play video placed in asset folder. Toast saying "Prepairing video..."
Log:
04-20 17:00:47.436: V/MediaPlayer(7065): prepareAsync
04-20 17:00:47.441: V/MediaPlayer(7065): message received msg=300, ext1=0, ext2=0
04-20 17:00:47.441: V/MediaPlayer(7065): Received SEC_MM_PLAYER_CONTEXT_AWARE
04-20 17:00:47.441: V/MediaPlayer(7065): callback application
04-20 17:00:47.441: V/MediaPlayer(7065): back from callback
04-20 17:00:47.441: V/MediaPlayer(7065): message received msg=100, ext1=1, ext2=-2147483648
04-20 17:00:47.441: E/MediaPlayer(7065): error (1, -2147483648)
04-20 17:00:47.441: V/MediaPlayer(7065): callback application
04-20 17:00:47.441: V/MediaPlayer(7065): back from callback
04-20 17:00:47.481: I/MediaPlayer(7065): send context aware event
04-20 17:00:47.486: I/MediaPlayer(7065): sendBroadcast CONTEXT_AWARE_MUSIC_INFO - type(error) - id (29)
04-20 17:00:47.486: E/MediaPlayer(7065): Error (1,-2147483648)

**Comment by 03lafaye** [comment]
I have it working on a Galaxy Note 4 model SM-N910H running 5.0.1. You can replace this 4k 30fps video with any other equirectangular video that you can load properly on your device.
