### ISSUE TITLE
Play Video On Button Click Not Working

### ISSUE THREAD

**Issue by debrajb** [fbsamples/360-video-player-for-android#7]
Button btn_play = (Button)findViewById(R.id.btn_play);  
btn_play.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {

```
                    videoPlayer = (SphericalVideoPlayer) findViewById(R.id.spherical_video_player);
                    videoPlayer.setVideoURIPath(SAMPLE_VIDEO_PATH);
                    videoPlayer.playWhenReady();
                    getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
                    requestExternalStoragePermission();

        }
        });
```

Not working....Please Help!!!!!!!!

**Comment by 03lafaye** [comment]
This isn't an issue with the project's code. Sorry, you'll have to debug your own code.
